# -*- mode: python ; coding: utf-8 -*-


# Wake-on-LAN Manager Version 2.1.0 - Dashboard Edition
# Generated on 2026-09-03

a = Analysis(
    ['run.py'],
    pathex=[],
    binaries=[],
    datas=[('icon.ico', '.'), ('icon_modern.ico', '.'), ('icon_modern.png', '.'), ('wol_app/locales/*.json', 'wol_app/locales')],
    hiddenimports=[
        'wol_app',
        'wol_app.__init__',
        'wol_app.config',
        'wol_app.crypto',
        'wol_app.device_dialog',
        'wol_app.log_dialog',
        'wol_app.main_window',
        'wol_app.network_scan_dialog',
        'wol_app.network_scanner',
        'wol_app.schedule_dialog',
        'wol_app.settings_dialog',
        'wol_app.translations',
        'wol_app.update_dialog',
        'wol_app.updater',
        'wol_app.utils',
        'wol_app.wol_engine',
        'wol_app.device_io',
        'wol_app.host_service_client',
        'wol_app.remote_desktop',
        'wol_app.scan_worker',
        'wol_app.schedule_runner',
        'wol_app.shutdown_flow',
        'wol_app.modern_main_window',
        'wol_app.modern_theme',
        'wol_app.theme',
        'wol_app.views',
        'wol_app.views.devices_view',
        'wol_app.views.device_edit_dialog',
        'wol_app.views.logs_view',
        'wol_app.views.manage_view',
        'wol_app.views.schedule_edit_dialog',
        'wol_app.views.schedule_view',
        'wol_app.views.settings_view',
        'wol_app.views.shutdown_confirm_dialog',
        'wol_app.views.update_view',
        'wol_app.widgets',
        'wol_app.widgets.toggle_switch',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Wake-on-LAN Manager',
    icon='icon.ico',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
